version: '3'
services:
  app:
    build:
      args:
        user: sandbox-atm
        uid: 1000
      context: .
      dockerfile: Dockerfile
    image: sandbox-atm
    container_name: sandbox-atm
    working_dir: /var/www
    volumes:
      - .:/var/www
  db:
    image: mysql
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_DATABASE: atm
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./.db:/var/lib/mysql
    ports:
      - '${DB_PORT:-3306}:3306'
